##################################################################################################
# Cart service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: cartdata
  labels:
    app: cartdata
    service: cartdata
spec:
  ports:
    - port: 6060
      name: http
  selector:
    app: cartdata
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart-data-app
  labels:
    account: cartdata
---
apiVersion: v1
kind: Deployment
metadata:
  name: cart-data-service
  labels:
    app: cartdata
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartdata
      version: v1
  template:
    metadata:
      labels:
        app: cartdata
        version: v1
    spec:
      serviceAccountName: cart-data-app
      containers:
        - name: cartdata
          image: docker.io/biswabhusan/cart-data-service:3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6060
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
